import Foundation
import AnycastKit

/// generateOPML (lib/widgets/import_export.dart:366-378) — the export writer,
/// ported as a pure function. AnycastKit owns the parser only; the writer
/// lives here so the AnycastKit sources stay untouched (T9 boundary).
///
/// Byte format = the Dart `opml` package (0.4.0) + `xml` package pretty
/// printer, verified against the real export fixture
/// `test/fixtures/opml/app_export.opml` (generated by the Dart code in M0):
///
///     <?xml version="1.0" encoding="UTF-8"?>
///     <opml version="2.0">
///       <head>
///         <title>Anycast Subscriptions</title>
///       </head>
///       <body>
///         <outline text="…" title="…" type="rss" xmlUrl="…" />
///       </body>
///     </opml>
///
/// (2-space indent, self-closing outlines, no trailing newline.) Attribute
/// order follows `OpmlOutline.toMap()`: text, title, type, xmlUrl — nulls are
/// dropped, exactly like the builder's `removeWhere`. The Dart writer force-
/// unwrapped `title!`/`description!` (crash family K4); the port's tolerance
/// is to omit a nil field instead of crashing.
nonisolated enum OPMLWriter {

    static let documentTitle = "Anycast Subscriptions"

    /// One `<outline>` per subscription, in the order given (the Dart writer
    /// received the live subscriptions list, already title-sorted upstream).
    static func document(subscriptions: [SubscriptionRow]) -> String {
        var lines: [String] = []
        lines.append(#"<?xml version="1.0" encoding="UTF-8"?>"#)
        lines.append(#"<opml version="2.0">"#)
        lines.append("  <head>")
        lines.append("    <title>\(escapeText(documentTitle))</title>")
        lines.append("  </head>")
        lines.append("  <body>")
        for subscription in subscriptions {
            var attributes: [(name: String, value: String)] = []
            if let text = subscription.description { attributes.append(("text", text)) }
            if let title = subscription.title { attributes.append(("title", title)) }
            attributes.append(("type", "rss"))
            if let xmlURL = subscription.rssFeedUrl { attributes.append(("xmlUrl", xmlURL)) }
            let rendered = attributes
                .map { #"\#($0.name)="\#(escapeAttribute($0.value))""# }
                .joined(separator: " ")
            lines.append("    <outline \(rendered)/>")
        }
        lines.append("  </body>")
        lines.append("</opml>")
        return lines.joined(separator: "\n")
    }

    // MARK: - xml-package escaping (xml 6.5.0 default mapping)

    /// `encodeText`: `&`, `<`, `]]>` and discouraged control codes.
    static func escapeText(_ input: String) -> String {
        var out = ""
        for scalar in input.unicodeScalars {
            switch scalar {
            case "&": out += "&amp;"
            case "<": out += "&lt;"
            case ">" where out.hasSuffix("]]"): out += "&gt;"
            default:
                if Self.isDiscouragedControl(scalar) {
                    out += numericReference(scalar)
                } else {
                    out.unicodeScalars.append(scalar)
                }
            }
        }
        return out
    }

    /// `encodeAttributeValue(.doubleQuote)`: `"`, `&`, `<`, newline,
    /// carriage return, tab and discouraged control codes. The fixture shows
    /// `\n` as `&#xA;` — uppercase hex character references.
    static func escapeAttribute(_ input: String) -> String {
        var out = ""
        for scalar in input.unicodeScalars {
            switch scalar {
            case "\"": out += "&quot;"
            case "&": out += "&amp;"
            case "<": out += "&lt;"
            case "\n": out += "&#xA;"
            case "\r": out += "&#xD;"
            case "\t": out += "&#x9;"
            default:
                if Self.isDiscouragedControl(scalar) {
                    out += numericReference(scalar)
                } else {
                    out.unicodeScalars.append(scalar)
                }
            }
        }
        return out
    }

    /// C0/C1 control codes the xml package escapes as numeric references
    /// (everything except NUL, HT, LF, CR and NEL, plus the discouraged
    /// 0x7F–0x84 / 0x86–0x9F ranges).
    private static func isDiscouragedControl(_ scalar: Unicode.Scalar) -> Bool {
        switch scalar.value {
        case 0x1...0x8, 0xB, 0xC, 0xE...0x1F, 0x7F...0x84, 0x86...0x9F:
            return true
        default:
            return false
        }
    }

    private static func numericReference(_ scalar: Unicode.Scalar) -> String {
        "&#x\(String(scalar.value, radix: 16, uppercase: true));"
    }
}
